# Generated by Django 5.1.6 on 2025-02-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone_num',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
